# Configurazione ossigeno
oxygen:
  max-oxygen: 200
  depletion-rate: 0.5
  helmet-boost: 2

# Configurazione del casco spaziale
spacehelmet:
  name: "§cCasco Spaziale"
  texture: "http://textures.minecraft.net/texture/d3530b3109d80796035d3cff3973b70e2cb73b925389f06cd4314a76099ba1d"