name: Gravity
version: 1.4.0
main: it.xgab05x.gravity.Gravity
api-version: 1.16


commands:
  gravity:
    description: Gestione della gravità
    usage: /gravity <comando>
    permission: gravity.*
    permission-message: "Non hai il permesso per eseguire questo comando."
    subcommands:
      exclude:
        description: Escludi un giocatore dalla gravità
        usage: /gravity exclude <giocatore>
        permission: gravity.exclude
        permission-message: "Non hai il permesso per eswcludere un player dal controllo gravità."
      include:
        description: Reincludi un giocatore al controllo della gravità
        usage: /gravity include <giocatore>
        permission: gravity.include
        permission-message: "Non hai il permesso per reincludere un player nel controllo gravità."
      excludedlist:
        description: Mostra la lista di giocatori esclusi
        usage: /gravity excludedlist
        permission: gravity.excludedlist
        permission-message: "Non hai il permesso per visualizzare i giocatori esclusi dal controllo gravità."
      reload:
        description: Ricarica il plugin
        usage: /gravity reload
        permission: gravity.*
        permission-message: "Non hai il permesso per ricaricare la configurazione."
      help:
        description: Mostra l'aiuto per i comandi
        usage: /gravity help
        permission: gravity.help
        permission-message: "Non hai il permesso per eseguire questo comando."
      wearspacehelmet:
        description: Indossa un casco spaziale per se stessi o per un altro giocatore
        usage: /gravity wearspacehelmet
        permission: gravity.helmetwear.self
        permission-message: "Non hai il permesso per indossare il casco spaziale."
        subcommands:
          others:
            description: Indossa un casco spaziale per un altro giocatore
            usage: /gravity wearspacehelmet <giocatore>
            permission: gravity.helmetwear.others
            permission-message: "Non hai il permesso per far indosssare un casco a un altro giocatore."

permissions:
  gravity.*:
    description: Accesso a tutti i comandi di gravità
    default: op
  gravity.exclude:
    description: Accesso al comando /gravity exclude
    default: op
  gravity.include:
    description: Accesso al comando /gravity include
    default: op
  gravity.excludedlist:
    description: Accesso al comando /gravity excludedlist
    default: op
  gravity.reload:
    description: Accesso al comando /gravity reload
    default: op
  gravity.help:
    description: Accesso al comando /gravity help
    default: true
  gravity.helmetwear.self:
    description: Permesso per indossare il casco spaziale su se stessi
    default: true
  gravity.helmetwear.others:
    description: Permesso per indossare il casco spaziale su un altro giocatore
    default: op